#!/bin/bash

# PUSH FILES, DIRECTORIES, OR RECURSIVE ALL TO LIVE SERVER
scriptName="$(basename $0)"

baseDir='/<example>/<local>/<path>'
targetDir='/<example>/<remote>/<path>'

inpOne
inpTwo

bold=$(tput bold)
normal=$(tput sgr0)

# CLEAR PREVIOUS CONSOLE OUTPUT
printf "\033c"

# HEADER INFO
echo ">> ${bold}${scriptName^^}${normal} >>"

# HELP INFO
if [[ $1 == "--help" ]];
then
  echo ""
  echo "valid cmd examples:"
  echo "$ ${bold}$scriptName index.html${normal}   will push -f arg to main -d"
  echo "$ ${bold}$scriptName css${normal}   will push -r -d arg to -d arg"
  echo "$ ${bold}$scriptName css/main.css css${normal}   will push -f arg to -d arg"
  echo "$ ${bold}$scriptName --files${normal}   will push /* to main -d"
  echo "$ ${bold}$scriptName --all${normal}   will push /* -r to main -d"


elif [[ $1 == "--setup" ]];
then
	read -p "Enter base directory: " inputFirst
	echo $inputFirst
	#sed -i 's/inpOne/$inputFirst' $scriptName
#
# KEYWORD ARGUMENTS
#

# PUSH ALL
elif [[ $1 == "--all" ]];
then
  sudo cp $baseDir/* -r $targetDir/
  echo "Pushing ${bold}$baseDir/* -r${normal} to ${bold}$targetDir/${normal}"

# PUSH FILES IN MAIN DIR
elif [[ $1 == "--files" ]];
then
  sudo cp $baseDir/* $targetDir/
  echo "Pushing ${bold}$baseDir/*${normal} to ${bold}$targetDir/${normal}";

# $1 FILE ARGUMENT, EX: $scriptName scripts/main.js [...]
elif [[ -f $ulDir/$1 ]];
then

  # $2 NO SERVER DIR ARG, EX: $scriptName scripts/main.js
  if [[ -z $2 ]];
  then
    read -p "Push ${bold}$baseDir/$1${normal} to ${bold}$targetDir/${normal}? ${bold}y/n${normal}: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      sudo cp $baseDir/$1 $targetDir/
      echo "Success! ${bold}$1${normal} has been updated."
    fi

  # $2 SERVER DIR ARG, EX: $scriptName scripts/main.js scripts
  elif [[ -d $baseDir/$2 ]];
  then
    sudo cp $baseDir/$1 $targetDir/$2/
    echo "Pushing ${bold}$baseDir/$1${normal} to ${bold}$targetDir/$2/${normal}"

  fi

# $1 DIR ARGUMENT, EX: scripts
elif [[ -d $baseDir/$1 && -z $2 ]];
then
  read -p "Push ${bold}$baseDir/$1${normal} to ${bold}$targetDir/${normal}? ${bold}y/n${normal}: " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    sudo cp $baseDir/$1/* -r $targetDir/$1/
    echo "Success! ${bold}$1/${normal} has been updated."
  fi

# ERROR, NO ARGUMENT
else
  echo "No argument. For more info use $ ${bold}$scriptName --help${normal}"
fi

echo ""

