#!/bin/sh

# PUSH FILES, DIRECTORIES, OR RECURSIVE ALL TO LIVE SERVER

# EX 1: pushverifydev index.html
# EX 2: pushverifydev scripts/main.js scripts
# EX 3: pushverifydev css
# EX 3: pushverifydev all

ulDir='/home/mursionweb/verify-dev'
servDir='/var/www/verify-dev'

bold=$(tput bold)
normal=$(tput sgr0)

# CLEAR PREVIOUS CONSOLE OUTPUT
printf "\033c"

# HEADER INFO
echo "-- PUSHVERIFYDEV --"

# HELP INFO
if [[ $1 == "-help" ]];
then
  echo ""
  echo "valid cmd examples:"
  echo "$ ${bold}pushverifydev index.html${normal}   will push -f arg to main -d"
  echo "$ ${bold}pushverifydev css${normal}   will push -r -d arg to -d arg"
  echo "$ ${bold}pushverifydev css/main.css css${normal}   [will push -f arg to -d arg"
  echo "$ ${bold}pushverifydev files${normal}   will push /* to main -d"
  echo "$ ${bold}pushverifydev all${normal}   will push /* -r to main -d"

# PUSH ALL
elif [[ $1 == "all" ]];
then
  sudo cp $ulDir/* -r $servDir/
  echo "Pushing ${bold}$ulDir/* -r${normal} to ${bold}$servDir/${normal}";

# PUSH FILES IN MAIN DIR
elif [[ $1 == "files" ]];
then
  sudo cp $ulDir/* $servDir/
  echo "Pushing ${bold}$ulDir/*${normal} to ${bold}$servDir/${normal}";

# $1 FILE ARGUMENT, EX: pushverifydev scripts/main.js [...]
elif [[ -f $ulDir/$1 ]];
then

  # $2 NO SERVER DIR ARG, EX: pushverifydev scripts/main.js
  if [[ -z $2 ]];
  then
    sudo cp $ulDir/$1 $servDir/
    echo "Pushing ${bold}$ulDir/$1${normal} to ${bold}$servDir/${normal}";

  # $2 SERVER DIR ARG, EX: pushverifydev scripts/main.js scripts
  elif [[ -d $ulDir/$2 ]];
  then
    sudo cp $ulDir/$1 $servDir/$2/
    echo "Pushing ${bold}$ulDir/$1${normal} to ${bold}$servDir/$2/${normal}";

  fi

# $1 DIR ARGUMENT, EX: scripts
elif [[ -d $ulDir/$1 && -z $2 ]];
then
  sudo cp $ulDir/$1/* -r $servDir/$1/
  echo "Pushing  ${bold}$ulDir/$1/*${normal} to ${bold}$servDir/$1/${normal}"
  #echo "pushed -d $1 -r to $servDir/$1/ b/c no server arg"

# ERROR, NO ARGUMENT
else
  echo "no argument";
fi

echo ""

